services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173"

    depends_on:
      - db
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: app_facilita
      MYSQL_USER: user
      MYSQL_PASSWORD: secret123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
